### ISSUE TITLE
Using a self signed SSL certificate

### ISSUE THREAD

**Issue by dprosper** [watsonwork/watsonwork-greeter#1]
The documentation for this sample suggest that the use of a self signed certificate is acceptable.  However, the steps to create the self signed certificate should be more specific.  if used as is the verification challenge never makes it to the sample app,  

change: 
openssl req -nodes -new -x509 -keyout server.key -out server.crt -subj "/CN=localhost"

to:
openssl req -nodes -new -x509 -keyout server.key -out server.crt -subj "/CN=< fully qualified host name >"
note: it is required to use a fully qualified host name that can be found in DNS, replace < fully qualified host name > in the above example with your host name.

**Comment by jsdelfino** [comment]
Thanks for reporting this! Will test this a bit more on my own server / host name and will make the necessary adjustments to the doc.
